window forge: app.window_open()
window walk: app.window_next()
window rewalk: app.window_previous()
window punch: app.window_close()
program walk: user.switcher_focus_last()
program <user.running_applications> walk: user.switcher_focus(running_applications)
