window forge: app.window_open()
window step: app.window_next()
window restep: app.window_previous()
window punch: app.window_close()
app step: user.switcher_focus_last()
app <user.running_applications> step: user.switcher_focus(running_applications)
