#!/usr/bin/env bash

set -eux

# Set the directory containing the preference files
pref_dir="$HOME/Library/Mobile\ Documents/com~apple~CloudDocs/Preferences"

# Get a list of preference files in the directory
pref_files=$(ls "$pref_dir")

# Loop through the list of preference files
for pref_file in $pref_files; do
  # Extract the domain name from the preference file name
  domain=$(echo "$pref_file" | sed 's/\.plist$//')

  # Import the preferences for the current domain from the file
  defaults import "$domain" "$pref_dir/$pref_file"
done
