#!/usr/bin/env bash

set -eux

# Usage: load-preferences <output directory>
# load-preferences /Users/jaresty/Library/Mobile\ Documents/com~apple~CloudDocs/Preferences/

# Get the output directory from the first script argument
input_dir=$1

# Ensure the input directory ends with a slash
input_dir=${input_dir%/}/

# Get a list of preference files in the directory
pref_files=$(ls "$input_dir")

# Loop through the list of preference files
for pref_file in $pref_files; do
  # Extract the domain name from the preference file name
  domain="${pref_file%.plist}"

  # Import the preferences for the current domain from the file
  defaults import "$domain" "$input_dir/$pref_file"
done
