#!/usr/bin/env bash

set -eux

domains=$(defaults domains | sed 's/,//g')

# Loop through the list of domains
for domain in $domains; do
  # Export the preferences for the current domain to a file
  defaults export "$domain" /Users/jaresty/Library/Mobile\ Documents/com~apple~CloudDocs/Preferences/"$domain.plist"
done
